version: '3'

services:
  webtop:
    image: 'lscr.io/linuxserver/webtop:fedora-kde'
    container_name: webtop
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/webtop/data:/config
    networks:
      - ngrok

  ngrok:
    image: 'ngrok/ngrok:latest'
    container_name: ngrok
    restart: unless-stopped
    depends_on:
      - webtop
    command:
      - "http"
      - "webtop:3000"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    networks:
      - ngrok

networks:
  ngrok:
    driver: "bridge"
